---
title: "CITE"
output: html_document
---

```{r init}
library(Seurat)
library(ggplot2)
library(patchwork)



# Load the dataset 

calr <- readRDS("/Users/lizacasella/Desktop/calr_data/calr.3p.rds")


```



```{r}
calr <- NormalizeData(calr)
# choose ~1k variable features
calr <- FindVariableFeatures(calr)
# standard scaling (no regression)
calr <- ScaleData(calr)
# Run PCA, select 13 PCs for tSNE visualization and graph-based clustering
calr <- RunPCA(calr, verbose = FALSE)
#ElbowPlot(calr, ndims = 50)
```

```{r}

adt <- calr@assays$ADT
calr <- NormalizeData(calr, assay = "ADT", normalization.method = "CLR")
calr <- ScaleData(calr, assay = "ADT")

names <- rownames(calr)

DefaultAssay(calr) <- "ADT"
calr <- RunPCA(calr, features = c("ADT_CD41","ADT_CD42b","ADT_CD45RA", "ADT_CD69", "ADT_CD9", "ADT_CD36", "ADT_CD38", "ADT_CD90","ADT_CD274_PDL1","ADT_CD279_PD1"), reduction.name = "pca_adt", reduction.key = "pca_adt_", verbose = FALSE)
DimPlot(calr) + NoLegend()



```

```{r}
calr <- FindNeighbors(calr, dims = 1:10)
calr <- FindClusters(calr, resolution = 0.5)
calr <- RunTSNE(calr, dims = 1:10, method = "FIt-SNE")
# Find the markers that define each cluster, and use these to annotate the clusters, we use
# max.cells.per.ident to speed up the process
calr.rna.markers <- FindAllMarkers(calr, max.cells.per.ident = 100, min.diff.pct = 0.3, only.pos = TRUE)


```



```{r}
new.cluster.ids <- c("Mono"  , "IMP/NP", "PreB6" , "PreB2" , "HSPC"  , "MEP9",   "PReB5" , "MEP0"  , "EBM","EP4"   , "MEP3" ,  "NA"  ,   "PreB11" ,"PreB8" , "MkP"  ,  "EP16"  , "PReB14" ,"MEP18")
names(new.cluster.ids) <- levels(calr)
calr <- RenameIdents(calr, new.cluster.ids)

X11()

DimPlot(calr, label = TRUE, group.by = "Cluster.Main") + NoLegend() 
dev.off()
while(names(dev.cur()) !='null device') Sys.sleep(1)


```


```{r}
# protein expression levels
calr[["ADT"]] <- CreateAssayObject(data=calr@meta.data$nCount_ADT)
calr <- NormalizeData(calr, assay = "ADT", normalization.method = "CLR")
calr <- ScaleData(calr, assay = "ADT")

FeaturePlot(calr, features = c("ADT_CD41", "ADT_CD69", "ADT_CD9", "ADT_CD36", "ADT_CD38", "ADT_CD90"), min.cutoff = "q05", max.cutoff = "q95", ncol = 3)


RidgePlot(calr, features = c("ADT_CD41", "ADT_CD90", "ADT_CD36", "ADT_CD38"), ncol = 2) 
```

```{r}

calr.small <- subset(calr, downsample = 300)

# Find protein markers for all clusters, and draw a heatmap
adt.markers <- FindAllMarkers(calr.small, assay = "ADT", only.pos = TRUE)
DoHeatmap(calr.small, features = unique(adt.markers$gene), assay = "ADT", angle = 90) + NoLegend()
```


```{r}
DefaultAssay(calr) <- "ADT"
calr <- RunPCA(calr, features = rownames(calr), reduction.name = "pca_adt", reduction.key = "pca_adt_", 
    verbose = FALSE)
DimPlot(calr, reduction = "pca_adt")




tsne_rnaClusters <- DimPlot(calr, reduction = "tsne_adt", group.by = "rnaClusterID") + NoLegend()
tsne_rnaClusters <- tsne_rnaClusters + ggtitle("Clustering based on scRNA-seq") + theme(plot.title = element_text(hjust = 0.5))
tsne_rnaClusters <- LabelClusters(plot = tsne_rnaClusters, id = "rnaClusterID", size = 4)

tsne_adtClusters <- DimPlot(calr, reduction = "tsne_adt", pt.size = 0.5) + NoLegend()
tsne_adtClusters <- tsne_adtClusters + ggtitle("Clustering based on ADT signal") + theme(plot.title = element_text(hjust = 0.5))
tsne_adtClusters <- LabelClusters(plot = tsne_adtClusters, id = "ident", size = 4)

# Note: for this comparison, both the RNA and protein clustering are visualized on a tSNE
# generated using the ADT distance matrix.
wrap_plots(list(tsne_rnaClusters, tsne_adtClusters), ncol = 2)
```

